server:
  port: 9000

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/practice
    username: dbadmin
    password: Ph03nix5parr0w!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
